### ISSUE TITLE
0.72 Update Request

### ISSUE THREAD

**Issue by ylluminate** [Sniki/HP6300-HP8300#1]
Hi Sniki! Thanks so much for your sharing this here. I've attempted to upgrade this from 0.63 to 0.72 three different times now and each time I've been met with failure where OC doesn't show the macOS drive upon boot. It seems as though something is not being upgraded properly in my cases, perhaps in the config.plist, but it is extremely baffling.

Could you please upgrade this to 0.72 and update accordingly? This would be an enormous help and I'd be fine if you need some kind of donation to help cover your time in making the update. This is a very frustrating situation in that there are some things I need via the new OC releases.

**Comment by donjakobo** [comment]
Are you referring to OpenCore v0.72 ?

You can just use the EFI partition and copy this over after initial install.  Use OpenCore to generate unique identifiers, and mount your EFI partition using something like https://github.com/headkaze/EFI-Agent (and copy the contents of this into the EFI partition).

My 6300 i7 boots beautiful after that, no issues to report. The OC v didn't matter to me, its having the kext/necessary EFI details in the correct partition (and of course unique serial etc generated)

**Comment by JohnAker33** [comment]
> Hi Sniki! Thanks so much for your sharing this here. I've attempted to upgrade this from 0.63 to 0.72 three different times now and each time I've been met with failure where OC doesn't show the macOS drive upon boot. It seems as though something is not being upgraded properly in my cases, perhaps in the config.plist, but it is extremely baffling.
> 
> Could you please upgrade this to 0.72 and update accordingly? 

One of the easiest ways update OpenCore is to use OpenCore Auxiliary Tools app. It's on Github. There is also a step by step guide.

**Comment by Sniki** [comment]
I have been busy with life lately however i do plan to make a future update to latest OpenCore and see if i can bring any improvements to that.

Please use forums instead, someone may be able to help you guys out until i return.
